version: '3'
services:
  db_import:
    build: db_import
    links:
      - mongodb.notinphilly.org 
    depends_on:
      - mongodb.notinphilly.org
  mongodb.notinphilly.org:
    image: mongo 
    ports: 
      - "27017:27017"
  web: 
    build: web 
    environment:
      - MONGO_DB_URL 
      - APP_NAME
      - DATABASE_NAME
      - NODEJS_IP
    ports: 
      - "8080:8080"
    links:
      - mongodb.notinphilly.org
    depends_on:
      - db_import 
